### ISSUE TITLE
Non-Square [W] matrix

### ISSUE THREAD

**Issue by jinjingfarm** [interpss/DeepMachineLearning#1]
When predicting branch flow, we would like to use a 2*noBus x noBranch [W], as follows:

```
W1 = tf.Variable(tf.zeros([2*noBus, noBranch]))
b1 = tf.Variable(tf.zeros([noBranch]))
```

However, we got the following error msg:

```
ValueError: setting an array element with a sequence.
```

Currently, we use a 2noBus x 2noBus [W] for predicting branch flow.

**Comment by Donghaoo** [comment]
@jinjingfarm it can run now on new branch. We should put a multidimensional array in the method 'np.array()'

**Comment by jinjingfarm** [comment]
this issue has been fixed with commit: https://github.com/interpss/DeepMachineLearning/commit/1aac0ddadcaf0c4b1fc476f4b43d4a9ffa6f13e6
