### ISSUE TITLE
Creating new test cases

### ISSUE THREAD

**Issue by BY-hash** [interpss/DeepMachineLearning#10]
Hello,

Is there any simple way to create more test cases (for example the ones from 1992 test feeder cases from ieee PES site) in the format of the test case used here (ieee-14.ieee)?

Any help appreciated!

**Comment by jinjingfarm** [comment]
@BY-hash We took an open approach for application of DML to power grid analysis. First, there is a way to extend to existing test case generation process to create more test cases. However, the extension needs some programming work. Therefore it might not be called a "simple way". Considering the varieties of power grid analysis tasks and large number of power system analysis input data format, realistically, there is not any simple way to the problem. You are encouraged to follow the [AclfTrainDataGenerator.java](https://github.com/interpss/DeepMachineLearning/blob/master/ipss.dml/src/org/interpss/service/AclfTrainDataGenerator.java) example to create your own test case creator.
