### ISSUE TITLE
 InterPSS Power System Model Service

### ISSUE THREAD

**Issue by jinjingfarm** [interpss/DeepMachineLearning#2]
Could you help me on how to start InterPSS Power System Model Service? The description you provided in the Wiki is given as follows:
 
·        Start InterPSS Power System Model Service

On Windows (or Linux) install and configure this Deep Machine Learning Repository, then start the AclfPyGateway InterPSS AclfNetwork model service. You should see the following output message, if the service is started and running:

Starting Py4J org.interpss.service.AclfPyGateway ...
 
And the interpss needs to be installed to coordinate, it will be great if you can also provide a quick guide on this.

**Comment by jinjingfarm** [comment]
As indicated by the ipss.dml/.classpath

https://github.com/interpss/DeepMachineLearning/blob/master/ipss.dml/.classpath

The project is depending on ipss.lib and ipss.lib.3rdPty.

**Comment by jinjingfarm** [comment]
The project Wiki page has been updated

https://github.com/interpss/DeepMachineLearning/wiki/Runtime-Env-Setup#run-the-sample-case

**Comment by thuang** [comment]
Since AclfPyGateway is a java file, I am wondering what is the proper bash script to be used for "starting the AclfPyGateway InterPSS AclfNetwork model service"  ??  Do I need to compile it and then run it as a Java program?

**Comment by jinjingfarm** [comment]
Yes，you need to compile it and then run it as a Java program.

**Comment by chutianzhixin87** [comment]
Thanks for all the helps. I'm running all these on a Linux machine and I have successfully complied the AclfPyGateway and run it. The output shows up "Starting Py4J org.interpss.service.AclfPyGateway ..."
