### ISSUE TITLE
Can anyone please guide on how to go on for installation from Scratch on Windows machine?

### ISSUE THREAD

**Issue by GirishVC86** [interpss/DeepMachineLearning#5]
I have followed the wiki environment setup
https://github.com/interpss/DeepMachineLearning/wiki/Runtime-Env-Setup

But cannot complete this point.

**Start InterPSS Power System Model Service**
On Windows (or Linux) install and configure this Deep Machine Learning Repository. The ipss.dml project is depending on the ipss.lib project and ipss.lib.3rdPty project in the InterPSS Common Repository. These two projects should also be checked out to your local machine. Then start the AclfPyGateway InterPSS AclfNetwork model service. You should see the following output message, if the service is started and running:

Starting Py4J org.interpss.service.AclfPyGateway ...

Can anyone please help in to provide configuring steps to be followed.

Thank You,
Girish

**Comment by jinjingfarm** [comment]
@DonghaoFeng Please work with LiuKai to create a step-by-step instruction for Windows.

**Comment by DonghaoFeng** [comment]
@GirishVC86 These two projects should be checked out to your local machine through following steps:
 1.From Eclipse, select File -­> import -> Git -> Projects from Git -> Clone URI.
 2.Add URI as follow: 1)https://github.com/InterPSS­Project/ipss­common.git;
   2) https://github.com/interpss/DeepMachineLearning.git
 3.Add the uer name and the password that you have applied on GitHub
 4.Select 'master' branch and then finish

**Comment by GirishVC86** [comment]
@DonghaoFeng It worked like charm. Thank you. Just out of curiosity how did you generate the test data? through InterPSS application?

**Comment by DonghaoFeng** [comment]
@GirishVC86 yes,the base case is ieee14.ieee
