### ISSUE TITLE
Dear DonghaoFeng, do you have some manual for your DML learning.

### ISSUE THREAD

**Issue by sirelays** [interpss/DeepMachineLearning#8]
Dear DonghaoFeng, do you have some manual for your DML including the software configuration?

Thank you very much.

**Comment by DonghaoFeng** [comment]
@sirelays please have a look https://github.com/interpss/DeepMachineLearning/wiki/%E4%BA%BA%E5%B7%A5%E6%99%BA%E8%83%BD%E8%AF%BE%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83%E9%83%A8%E7%BD%B2
